"""Bulk-copy a whole library from one backend to another.

Switching ``[database] backend`` does not move any data: the new database starts
empty, and re-populating it the normal way would mean a fresh ``sync`` plus a
multi-hour ``extract``. This is the shortcut — a straight table-by-table copy of
the SQLite file into the configured external database.

It is deliberately not a job (no ``JOB_SPECS`` entry), for the same reason
``reset-password`` is not: it rewrites the destination wholesale, and the only
sensible time to run it is once, from a shell, with both databases quiescent.
"""

from __future__ import annotations

import logging
from typing import Callable

from .connection import Connection
from .dialect import scan_identity_columns

log = logging.getLogger("synopticon.db")

#: Every table, ordered so a row's foreign-key targets are always copied first.
#: `embeddings`/`cluster_members` reference `faces`; `clusters` references
#: `cluster_runs`; `audit_log` references `review_queue`; `web_sessions`
#: references `web_users`; `schedule_runs` references `schedules`.
TABLES: tuple[str, ...] = (
    "photos",
    "persons",
    "person_photos",
    "syno_faces",
    "faces",
    "embeddings",
    "cluster_runs",
    "clusters",
    "cluster_members",
    "review_queue",
    "audit_log",
    "sync_state",
    "extract_log",
    "web_users",
    "web_sessions",
    "web_api_keys",
    "schedules",
    "schedule_runs",
)

#: Rows read and written per round trip. Large enough to amortise the network
#: round trip, small enough that a 56k-face `embeddings` table (a 512-float blob
#: per row) does not have to fit in memory all at once.
BATCH = 1000

Progress = Callable[[str, int, int | None], None]


def non_empty_tables(conn: Connection) -> dict[str, int]:
    """Row counts for every table that has any, used as the "is it safe" check."""
    from .store import table_exists

    counts: dict[str, int] = {}
    for table in TABLES:
        if not table_exists(conn, table):
            continue
        row = conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()
        n = int(row[0]) if row else 0
        if n:
            counts[table] = n
    return counts


def copy_database(
    source: Connection,
    target: Connection,
    progress: Progress | None = None,
) -> dict[str, int]:
    """Copy every table from ``source`` into ``target``; returns rows per table.

    ``target`` must already carry the schema (``store.connect`` migrates on open)
    and should be empty — a caller that skips :func:`non_empty_tables` will get
    duplicate-key failures rather than silent merging, which is the safer of the
    two outcomes but still not a supported mode.
    """
    from .store import table_exists

    copied: dict[str, int] = {}
    for table in TABLES:
        if not table_exists(source, table):
            continue
        copied[table] = _copy_table(source, target, table, progress)
        target.commit()
    _reset_identity_sequences(target)
    target.commit()
    return copied


def _copy_table(
    source: Connection, target: Connection, table: str, progress: Progress | None
) -> int:
    total_row = source.execute(f"SELECT COUNT(*) FROM {table}").fetchone()
    total = int(total_row[0]) if total_row else 0
    if progress:
        progress(table, 0, total)
    if not total:
        return 0

    cursor = source.execute(f"SELECT * FROM {table}")
    columns = [d[0] for d in cursor.description]
    placeholders = ",".join("?" * len(columns))
    insert = (
        f"INSERT INTO {table} ({', '.join(columns)}) VALUES ({placeholders})"
    )

    done = 0
    while True:
        rows = cursor.fetchmany(BATCH)
        if not rows:
            break
        target.executemany(insert, [tuple(r) for r in rows])
        done += len(rows)
        if progress:
            progress(table, done, total)
    log.info("copied %s rows from %s", done, table)
    return done


def _reset_identity_sequences(target: Connection) -> None:
    """Point each identity sequence past the ids we just inserted.

    Copied rows carry their original primary keys, which the ``GENERATED BY
    DEFAULT AS IDENTITY`` columns accept — but the underlying sequence is still
    at 1, so the very next insert would collide. Nothing to do on SQLite, whose
    ``AUTOINCREMENT`` counter derives from the table itself.
    """
    if target.dialect.name != "postgres":
        return
    from .store import _MIGRATIONS

    identity = scan_identity_columns([m.read_text() for m in _MIGRATIONS])
    for table, column in identity.items():
        target.execute(
            f"SELECT setval(pg_get_serial_sequence('{table}', '{column}'), "
            f"COALESCE(MAX({column}), 1), MAX({column}) IS NOT NULL) FROM {table}"
        )
