"""SQL dialect translation — the layer that lets one set of SQL serve two backends.

These run without any database. The PostgreSQL round trip is covered by
``test_postgres_backend.py``, which needs a real server.
"""

from __future__ import annotations

import pytest

from synopticon.db import store
from synopticon.db.dialect import (
    Dialect,
    PostgresDialect,
    is_pragma,
    scan_identity_columns,
    split_script,
)

PG = PostgresDialect({"faces": "face_id", "audit_log": "id"})


class TestPlaceholders:
    def test_question_marks_become_percent_s(self):
        assert (
            PG.translate("SELECT * FROM photos WHERE space = ? AND id = ?", True)
            == "SELECT * FROM photos WHERE space = %s AND id = %s"
        )

    def test_question_mark_inside_a_literal_is_data(self):
        sql = "SELECT ? FROM t WHERE name = 'who? me'"
        assert PG.translate(sql, True) == "SELECT %s FROM t WHERE name = 'who? me'"

    def test_question_mark_inside_a_comment_is_left_alone(self):
        sql = "SELECT ? FROM t -- why? because\n"
        assert PG.translate(sql, True) == "SELECT %s FROM t -- why? because\n"

    def test_percent_is_escaped_only_when_binding(self):
        # psycopg skips placeholder parsing entirely for a parameterless
        # statement, so escaping there would leave a literal '%%' in the SQL.
        sql = "SELECT * FROM t WHERE name LIKE 'a%'"
        assert PG.translate(sql, True) == "SELECT * FROM t WHERE name LIKE 'a%%'"
        assert PG.translate(sql, False) == sql

    def test_doubled_quote_escape_does_not_end_the_literal(self):
        sql = "SELECT 'it''s ? here' , ?"
        assert PG.translate(sql, True) == "SELECT 'it''s ? here' , %s"

    def test_sqlite_dialect_is_byte_identical_passthrough(self):
        sql = "SELECT * FROM t WHERE a = ? AND b LIKE '%x%'"
        assert Dialect().translate(sql, True) == sql
        assert Dialect().translate_ddl(sql) == sql


class TestNullSafeComparison:
    def test_is_not_becomes_is_distinct_from(self):
        # PostgreSQL has no `a IS NOT b`; without this it is a bare syntax error.
        sql = "SELECT 1 FROM t WHERE e.cache_key IS NOT p.cache_key"
        assert PG.translate(sql, False) == (
            "SELECT 1 FROM t WHERE e.cache_key IS DISTINCT FROM p.cache_key"
        )

    def test_is_becomes_is_not_distinct_from(self):
        sql = "SELECT 1 FROM t WHERE a IS b"
        assert PG.translate(sql, False) == "SELECT 1 FROM t WHERE a IS NOT DISTINCT FROM b"

    def test_unary_predicates_are_left_alone(self):
        sql = "SELECT 1 FROM t WHERE a IS NULL OR b IS NOT NULL OR c IS NOT TRUE OR d IS FALSE"
        assert PG.translate(sql, False) == sql

    def test_already_standard_form_is_untouched(self):
        sql = "SELECT 1 FROM t WHERE a IS DISTINCT FROM b"
        assert PG.translate(sql, False) == sql

    def test_placeholder_operand_is_rewritten(self):
        sql = "SELECT 1 FROM t WHERE a IS NOT ?"
        assert PG.translate(sql, True) == "SELECT 1 FROM t WHERE a IS DISTINCT FROM %s"

    def test_literal_operand_across_a_chunk_boundary_is_rewritten(self):
        # The scanner ends the code chunk at the quote, so the match runs to the
        # end of the chunk — which only happens for a value comparison.
        sql = "SELECT 1 FROM t WHERE a IS NOT 'x'"
        assert PG.translate(sql, False) == "SELECT 1 FROM t WHERE a IS DISTINCT FROM 'x'"

    def test_operator_inside_a_literal_or_comment_is_data(self):
        assert PG.translate("SELECT 'a IS NOT b' FROM t", False) == "SELECT 'a IS NOT b' FROM t"
        assert PG.translate("SELECT 1 -- a IS NOT b\n", False) == "SELECT 1 -- a IS NOT b\n"

    def test_sqlite_keeps_its_own_spelling(self):
        sql = "SELECT 1 FROM t WHERE a IS NOT b"
        assert Dialect().translate(sql, False) == sql


class TestDDLTranslation:
    def test_autoincrement_becomes_an_identity_column(self):
        out = PG.translate_ddl("CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT)")
        assert "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in out
        assert "AUTOINCREMENT" not in out

    def test_integer_widens_to_bigint(self):
        # PostgreSQL INTEGER is int4 where SQLite's is int8, and photos.indexed_time
        # holds epoch milliseconds — int4 overflows on the first row written.
        out = PG.translate_ddl("CREATE TABLE t (indexed_time INTEGER NOT NULL)")
        assert out == "CREATE TABLE t (indexed_time BIGINT NOT NULL)"

    def test_identity_column_is_not_double_translated(self):
        out = PG.translate_ddl("CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT)")
        assert "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in out
        assert "BIGINT BIGINT" not in out

    def test_blob_becomes_bytea(self):
        assert "BYTEA" in PG.translate_ddl("CREATE TABLE t (vec BLOB NOT NULL)")

    def test_real_widens_to_double_precision(self):
        # PostgreSQL REAL is float4. Face bboxes are part of a UNIQUE key, so
        # narrowing them would collapse distinct detections into a violation.
        out = PG.translate_ddl("CREATE TABLE t (x REAL NOT NULL, y REAL)")
        assert out.count("DOUBLE PRECISION") == 2

    def test_comments_are_dropped_not_translated(self):
        out = PG.translate_ddl("-- a REAL BLOB of prose\nCREATE TABLE t (a TEXT)")
        assert "DOUBLE PRECISION" not in out and "BYTEA" not in out
        assert "CREATE TABLE t (a TEXT)" in out

    def test_json_extract_becomes_a_jsonb_path(self):
        out = PG.translate_ddl(
            "UPDATE q SET k = 'x' WHERE json_extract(payload_json, '$.person_a.name') <> ''"
        )
        assert "(payload_json::jsonb #>> '{person_a,name}')" in out
        assert "json_extract" not in out


class TestScriptSplitting:
    def test_splits_on_statement_boundaries(self):
        assert split_script("CREATE TABLE a (x INT); CREATE TABLE b (y INT);") == [
            "CREATE TABLE a (x INT)",
            "CREATE TABLE b (y INT)",
        ]

    def test_semicolon_inside_a_literal_does_not_split(self):
        assert split_script("INSERT INTO t VALUES ('a;b'); SELECT 1;") == [
            "INSERT INTO t VALUES ('a;b')",
            "SELECT 1",
        ]

    def test_comment_only_fragments_are_dropped(self):
        assert split_script("-- just a note\n\n-- another\n") == []

    def test_is_pragma(self):
        assert is_pragma("PRAGMA user_version") and is_pragma("  pragma foreign_keys=ON")
        assert not is_pragma("SELECT 1")


class TestIdentityDiscovery:
    def test_scans_autoincrement_columns_out_of_ddl(self):
        found = scan_identity_columns(
            [
                "CREATE TABLE faces (\n    face_id INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                "    space TEXT\n);\n"
                "CREATE TABLE plain (\n    id INTEGER NOT NULL\n);"
            ]
        )
        assert found == {"faces": "face_id"}

    def test_real_schema_identity_columns_are_all_found(self):
        # Guards the RETURNING path: a table missing here silently returns
        # lastrowid=None on PostgreSQL.
        found = scan_identity_columns([m.read_text() for m in store._MIGRATIONS])
        assert found == {
            "faces": "face_id",
            "cluster_runs": "run_id",
            "review_queue": "item_id",
            "audit_log": "id",
            "web_users": "id",
            "web_api_keys": "id",
            "web_recovery_codes": "id",
            "web_auth_log": "id",
            "schedules": "id",
            "schedule_runs": "id",
        }


class TestReturning:
    def test_insert_into_an_identity_table_gets_returning(self):
        assert PG.returning_clause("INSERT INTO faces (a) VALUES (1)") == " RETURNING face_id"

    def test_insert_into_a_plain_table_does_not(self):
        assert PG.returning_clause("INSERT INTO photos (a) VALUES (1)") is None

    def test_non_inserts_and_existing_returning_are_left_alone(self):
        assert PG.returning_clause("SELECT * FROM faces") is None
        assert PG.returning_clause("INSERT INTO faces (a) VALUES (1) RETURNING face_id") is None

    def test_sqlite_never_appends_returning(self):
        assert Dialect().returning_clause("INSERT INTO faces (a) VALUES (1)") is None


class TestEveryMigrationTranslates:
    @pytest.mark.parametrize("migration", store._MIGRATIONS, ids=lambda m: m.name)
    def test_no_sqlite_only_syntax_survives(self, migration):
        for statement in split_script(migration.read_text()):
            out = PG.translate_ddl(statement)
            assert "AUTOINCREMENT" not in out.upper()
            assert "json_extract" not in out
            assert not [w for w in out.split() if w.upper().strip("(),") == "BLOB"]
            assert not [w for w in out.split() if w.upper().strip("(),") == "INTEGER"]


def _declared_integer_columns() -> dict[str, set[str]]:
    """`{table: {int columns}}` as the migrations *before* the widening one declare them.

    0009 is a historical repair for PostgreSQL databases created before the DDL
    translator emitted BIGINT. From version 10 on, every migration goes through
    `translate_ddl` on fresh and upgrading installs alike, so its INTEGER is
    already BIGINT everywhere and there is nothing left to widen.
    """
    import re

    tables: dict[str, set[str]] = {}
    pg_only = next(m for m in store._MIGRATIONS if m.name.endswith(".pg.sql"))
    for migration in store._MIGRATIONS[: store._MIGRATIONS.index(pg_only)]:
        sql = migration.read_text()
        for m in re.finditer(
            r"ALTER\s+TABLE\s+(\w+)\s+ADD\s+COLUMN\s+(\w+)\s+INTEGER", sql, re.I
        ):
            tables.setdefault(m.group(1).lower(), set()).add(m.group(2))
        for m in re.finditer(
            r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(\w+)\s*\((.*?)\n\);",
            sql,
            re.I | re.S,
        ):
            table, body = m.group(1).lower(), m.group(2)
            for line in body.splitlines():
                col = re.match(r"\s*(\w+)\s+INTEGER\b(?!\s+PRIMARY\s+KEY\s+AUTOINCREMENT)",
                               line, re.I)
                if col:
                    tables.setdefault(table, set()).add(col.group(1))
    return tables


def _widened_columns() -> dict[str, set[str]]:
    """`{table: {columns}}` the widening migration actually alters."""
    import re

    widened: dict[str, set[str]] = {}
    pg_only = next(m for m in store._MIGRATIONS if m.name.endswith(".pg.sql"))
    for statement in split_script(pg_only.read_text()):
        statement = PG.translate_ddl(statement)  # drops the leading comment block
        table = re.match(r"\s*ALTER\s+TABLE\s+(\w+)", statement, re.I)
        assert table, statement
        widened[table.group(1).lower()] = {
            m.group(1)
            for m in re.finditer(r"ALTER\s+COLUMN\s+(\w+)\s+TYPE\s+BIGINT", statement, re.I)
        }
    return widened


class TestIntegerWidening:
    def test_it_covers_exactly_the_integer_columns_the_schema_declares(self):
        # The DDL translator makes a *fresh* PostgreSQL database bigint; this
        # migration is what brings an existing one to the same shape. A column
        # missing here is one that stays capped at 2.1e9 only on upgraded
        # installs — the hardest kind of divergence to notice.
        assert _widened_columns() == _declared_integer_columns()


class TestBackendScopedMigrations:
    def test_pg_only_migration_is_skipped_on_sqlite(self, tmp_path):
        pg_only = next(m for m in store._MIGRATIONS if m.name.endswith(".pg.sql"))
        assert not store._applies_to(pg_only, "sqlite")
        assert store._applies_to(pg_only, "postgres")

    def test_shared_migrations_apply_everywhere(self):
        shared = next(m for m in store._MIGRATIONS if not m.name.endswith(".pg.sql"))
        assert store._applies_to(shared, "sqlite")
        assert store._applies_to(shared, "postgres")

    def test_a_skipped_migration_still_consumes_its_version(self, tmp_path):
        # Otherwise SQLite would stay one version behind forever and re-run the
        # tail of the list on every single connect.
        conn = store.connect(tmp_path / "s.db")
        try:
            assert conn.execute("PRAGMA user_version").fetchone()[0] == len(store._MIGRATIONS)
        finally:
            conn.close()

    def test_epoch_milliseconds_round_trip_on_sqlite(self, tmp_path):
        conn = store.connect(tmp_path / "s.db")
        try:
            ms = 1_755_000_000_000
            conn.execute(
                "INSERT INTO photos (id, space, indexed_time, synced_at, deleted) "
                "VALUES (?,?,?,?,0)",
                (1, "personal", ms, 0),
            )
            conn.commit()
            assert conn.execute("SELECT indexed_time FROM photos").fetchone()[0] == ms
        finally:
            conn.close()
