"""SQL dialect translation — the layer that lets one set of SQL serve two backends.

These run without any database. The PostgreSQL round trip is covered by
``test_postgres_backend.py``, which needs a real server.
"""

from __future__ import annotations

import pytest

from synopticon.db import store
from synopticon.db.dialect import (
    Dialect,
    PostgresDialect,
    is_pragma,
    scan_identity_columns,
    split_script,
)

PG = PostgresDialect({"faces": "face_id", "audit_log": "id"})


class TestPlaceholders:
    def test_question_marks_become_percent_s(self):
        assert (
            PG.translate("SELECT * FROM photos WHERE space = ? AND id = ?", True)
            == "SELECT * FROM photos WHERE space = %s AND id = %s"
        )

    def test_question_mark_inside_a_literal_is_data(self):
        sql = "SELECT ? FROM t WHERE name = 'who? me'"
        assert PG.translate(sql, True) == "SELECT %s FROM t WHERE name = 'who? me'"

    def test_question_mark_inside_a_comment_is_left_alone(self):
        sql = "SELECT ? FROM t -- why? because\n"
        assert PG.translate(sql, True) == "SELECT %s FROM t -- why? because\n"

    def test_percent_is_escaped_only_when_binding(self):
        # psycopg skips placeholder parsing entirely for a parameterless
        # statement, so escaping there would leave a literal '%%' in the SQL.
        sql = "SELECT * FROM t WHERE name LIKE 'a%'"
        assert PG.translate(sql, True) == "SELECT * FROM t WHERE name LIKE 'a%%'"
        assert PG.translate(sql, False) == sql

    def test_doubled_quote_escape_does_not_end_the_literal(self):
        sql = "SELECT 'it''s ? here' , ?"
        assert PG.translate(sql, True) == "SELECT 'it''s ? here' , %s"

    def test_sqlite_dialect_is_byte_identical_passthrough(self):
        sql = "SELECT * FROM t WHERE a = ? AND b LIKE '%x%'"
        assert Dialect().translate(sql, True) == sql
        assert Dialect().translate_ddl(sql) == sql


class TestDDLTranslation:
    def test_autoincrement_becomes_an_identity_column(self):
        out = PG.translate_ddl("CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT)")
        assert "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in out
        assert "AUTOINCREMENT" not in out

    def test_blob_becomes_bytea(self):
        assert "BYTEA" in PG.translate_ddl("CREATE TABLE t (vec BLOB NOT NULL)")

    def test_real_widens_to_double_precision(self):
        # PostgreSQL REAL is float4. Face bboxes are part of a UNIQUE key, so
        # narrowing them would collapse distinct detections into a violation.
        out = PG.translate_ddl("CREATE TABLE t (x REAL NOT NULL, y REAL)")
        assert out.count("DOUBLE PRECISION") == 2

    def test_comments_are_dropped_not_translated(self):
        out = PG.translate_ddl("-- a REAL BLOB of prose\nCREATE TABLE t (a TEXT)")
        assert "DOUBLE PRECISION" not in out and "BYTEA" not in out
        assert "CREATE TABLE t (a TEXT)" in out

    def test_json_extract_becomes_a_jsonb_path(self):
        out = PG.translate_ddl(
            "UPDATE q SET k = 'x' WHERE json_extract(payload_json, '$.person_a.name') <> ''"
        )
        assert "(payload_json::jsonb #>> '{person_a,name}')" in out
        assert "json_extract" not in out


class TestScriptSplitting:
    def test_splits_on_statement_boundaries(self):
        assert split_script("CREATE TABLE a (x INT); CREATE TABLE b (y INT);") == [
            "CREATE TABLE a (x INT)",
            "CREATE TABLE b (y INT)",
        ]

    def test_semicolon_inside_a_literal_does_not_split(self):
        assert split_script("INSERT INTO t VALUES ('a;b'); SELECT 1;") == [
            "INSERT INTO t VALUES ('a;b')",
            "SELECT 1",
        ]

    def test_comment_only_fragments_are_dropped(self):
        assert split_script("-- just a note\n\n-- another\n") == []

    def test_is_pragma(self):
        assert is_pragma("PRAGMA user_version") and is_pragma("  pragma foreign_keys=ON")
        assert not is_pragma("SELECT 1")


class TestIdentityDiscovery:
    def test_scans_autoincrement_columns_out_of_ddl(self):
        found = scan_identity_columns(
            [
                "CREATE TABLE faces (\n    face_id INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                "    space TEXT\n);\n"
                "CREATE TABLE plain (\n    id INTEGER NOT NULL\n);"
            ]
        )
        assert found == {"faces": "face_id"}

    def test_real_schema_identity_columns_are_all_found(self):
        # Guards the RETURNING path: a table missing here silently returns
        # lastrowid=None on PostgreSQL.
        found = scan_identity_columns([m.read_text() for m in store._MIGRATIONS])
        assert found == {
            "faces": "face_id",
            "cluster_runs": "run_id",
            "review_queue": "item_id",
            "audit_log": "id",
            "web_users": "id",
            "web_api_keys": "id",
            "schedules": "id",
            "schedule_runs": "id",
        }


class TestReturning:
    def test_insert_into_an_identity_table_gets_returning(self):
        assert PG.returning_clause("INSERT INTO faces (a) VALUES (1)") == " RETURNING face_id"

    def test_insert_into_a_plain_table_does_not(self):
        assert PG.returning_clause("INSERT INTO photos (a) VALUES (1)") is None

    def test_non_inserts_and_existing_returning_are_left_alone(self):
        assert PG.returning_clause("SELECT * FROM faces") is None
        assert PG.returning_clause("INSERT INTO faces (a) VALUES (1) RETURNING face_id") is None

    def test_sqlite_never_appends_returning(self):
        assert Dialect().returning_clause("INSERT INTO faces (a) VALUES (1)") is None


class TestEveryMigrationTranslates:
    @pytest.mark.parametrize("migration", store._MIGRATIONS, ids=lambda m: m.name)
    def test_no_sqlite_only_syntax_survives(self, migration):
        for statement in split_script(migration.read_text()):
            out = PG.translate_ddl(statement)
            assert "AUTOINCREMENT" not in out.upper()
            assert "json_extract" not in out
            assert not [w for w in out.split() if w.upper().strip("(),") == "BLOB"]
